from app.config.config import (
    API_V1_STR,
    PROJECT_NAME,
    MODEL_CACHE_DIR,
    DEFAULT_USER_AGENT,
    MAX_PAGE_SCROLLS,
    SCAN_TIMEOUT_SEC,
    DNS_RESOLVERS,
)

__all__ = [
    "API_V1_STR",
    "PROJECT_NAME",
    "MODEL_CACHE_DIR",
    "DEFAULT_USER_AGENT",
    "MAX_PAGE_SCROLLS",
    "SCAN_TIMEOUT_SEC",
    "DNS_RESOLVERS",
]
